{{- if not .Values.pipelines.existingInputsConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quay-provisioner.inputsConfigMapName" . }}
  labels:
    {{- include "quay-provisioner.labels" . | nindent 4 }}
data:
  inputs.yaml: |
    {{- toYaml .Values.pipelines.inputs | nindent 4 }}
{{- end }}