{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quay-provisioner.secretName" . }}
  labels:
    {{- include "quay-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.secrets.apiToken | quote }}
{{- end }}