# Build logs Redis configuration
BUILDLOGS_REDIS:
  host: quay-redis
  port: 6379
CREATE_NAMESPACE_ON_PUSH: true
DATABASE_SECRET_KEY: a8c2744b-7004-4af2-bcee-e417e7bdd235
DB_URI: postgresql://quay:quay@quay-pg-db:5432/quay
DISTRIBUTED_STORAGE_CONFIG:
  default:
    - LocalStorage
    - storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: [ ]
DISTRIBUTED_STORAGE_PREFERENCE:
  - default
FEATURE_MAILING: false
FEATURE_PROXY_CACHE: true
SECRET_KEY: e9bd34f4-900c-436a-979e-7530e5d74ac8
# Server configuration
SERVER_HOSTNAME: 127.0.0.1:9080
SETUP_COMPLETE: true

# User events Redis configuration
USER_EVENTS_REDIS:
  host: quay-redis
  port: 6379

PROXY_CACHE_CONFIG:
  redis_host: quay-redis
  redis_port: 6379

# Superuser configuration
SUPER_USERS:
  - admin